### ISSUE TITLE
Rails 5.1:  Directly inheriting from ActiveRecord::Migration is not supported

### ISSUE THREAD

**Issue by drernie** [code-mancers/rapidfire#100]
Need to append the Rails version number, as in:
```
class CreateRapidfireQuestionGroups < ActiveRecord::Migration[5.1]
```
I'm not sure what version they started requiring this, but I saw it in 5.1.

**Comment by aksh93** [comment]
This issue has been resolved [#118](https://github.com/code-mancers/rapidfire/pull/118).
