### ISSUE TITLE
When using checkboxes, validation always fails

### ISSUE THREAD

**Issue by codeodor** [code-mancers/rapidfire#114]
Because in the attempt builder, `text` is `<ActionController::Parameters {"0"=>"0", "1"=>"0", "2"=>"0", "3"=>"0", "4"=>"0", "5"=>"0"} permitted: true>`, not an array, to that string "<ActionController::Parameters {"0"=>"0", "1"=>"0", "2"=>"0", "3"=>"0", "4"=>"0", "5"=>"0"} permitted: true>" gets set as the answer.

**Comment by codeodor** [comment]
Even that fix does not complete it unless the values include "0", since Rails will submit 0 for unchecked checkboxes. I will work on that as well.

**Comment by codeodor** [comment]
Ok, that fix should be good now.

**Comment by dflorez6** [comment]
Is there a fix to this problem. I've been trying to use checkboxes, but I always get the same error: "Answer text is invalid"

**Comment by codeodor** [comment]
I've just been using my own fork of this project, which has that fix and many more improvements (at least for my use-case).

See #115 for my fix for only this issue, or #113 for all of them.

**Comment by dflorez6** [comment]
Thanks for your reply, I'm just gonna go with a custom solution for what I need. Thanks again.
