### ISSUE TITLE
undefined method `before_filter' for Rapidfire::SurveysController:Class Did you mean? before_action

### ISSUE THREAD

**Issue by reynold2468** [code-mancers/rapidfire#123]
Hi,
I am following the documentation and on the usage step I get this error when I try to load my http://localhost:3000/rapidfire page.  Although this issue is taken care of in the surveys controller , I still keep getting this error.

**Comment by aksh93** [comment]
Hi @reynold2468 ,
Build for Rails 5.1.x has not been released yet. But you could make use of the latest code by providing the git path to the repository within the gem file.
`gem 'rapidfire', git: 'https://github.com/code-mancers/rapidfire.git'`

**Comment by reynold2468** [comment]
Thanks for the update, I appreciate it. Looking forward to the release.
Thanks,
Best Regards,
Reynold Dmello.
