### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by joseramonc** [code-mancers/rapidfire#16]
I have an issue were I have links for my differents controllers of my app and for the rapidfire index on application.html.erb; the links work good when I'm in my controllers links, but when I go to the rapidfire path i get undefined local variable or method 'mymodel_path' is there a clean way to fix this?

**Comment by albertpak** [comment]
Im running into same issue...followed the guide and now im getting an error that ```undefined method `new_user_session_path'```

found this thread on SO - http://stackoverflow.com/questions/19437830/rapidfire-gem-and-undefined-local-variable-or-method-when-loged-in-survey-creat - but by adding my_app to the paths that are causing errors, all styling and rest of the paths break...

any solution for this issue?

I'm using Ruby 2.1.3, Rails 3.2.21 and Rapidfire 2.0.0

**Comment by iffyuva** [comment]
do you have any example code which i can look at?

**Comment by albertpak** [comment]
__Error__:
```ruby
NameError at /
undefined local variable or method `new_user_session_path' for #<#<Class:0x007f83e6200ca8>:0x007f83e68ad128>
```

__Code__:
```html
<li>
   <%= link_to('Login', new_user_session_path) %>
</li>
```

**Comment by iffyuva** [comment]
i guess you can use `main_app.new_user_session_path`

**Comment by albertpak** [comment]
yeah, I've already tried that, after I add that to that link, then it tells me that another one and anther one, after i add 'main_app' to the links that are causing issues - i works, but when i go to localhost:3000/survey - all my styles are broken

**Comment by iffyuva** [comment]
is it possible to have a sample app to demonstrate this?

**Comment by albertpak** [comment]
no, i can't dump whole app onto github's public repo

**Comment by iffyuva** [comment]
not the whole app, but if you can trim down code in order to reproduce this issue, it would be great.

**Comment by albertpak** [comment]
I have roles, cancan and modded devise in it, not sure how to strip it down to replicate the error...
