### ISSUE TITLE
add an option to answer builder to fetch and update existing answers

### ISSUE THREAD

**Issue by iffyuva** [code-mancers/rapidfire#17]
right now `AnswerGroupBuilder` always creates a new set of answers. Give an option to update existings answers.

**Comment by marcolong** [comment]
Any news?
I'm trying to do it this way, I know it's not the best one:
```ruby
def build_answer_group
      @answer_group = AnswerGroup.where(user: user, question_group: question_group).first_or_create
      if @answer_group.answers.blank? 
        @answers = @question_group.questions.collect do |question|
          @answer_group.answers.build(question_id: question.id)
        end
      else
        @answers = @answer_group.answers
      end
    end
```
Moreover, I've added a field to AnswerGroup to know if the survey is completed, because I give to users only one attempt.

**Comment by iffyuva** [comment]
the code is in a separate branch, i have to bring it to latest master, and make a release.

code reference: https://github.com/code-mancers/rapidfire/commit/43f285f7de341da1102df2133ef4663cf2065ed8

**Comment by marcolong** [comment]
Great job!

**Comment by brunoocasali** [comment]
What about this issue, will be merged? is insecure use this in my production app?

**Comment by iffyuva** [comment]
@brunoocasali this should get merged. i added this issue to never ending v3.0.0 release. hopefully should be able to release it soon.

**Comment by iffyuva** [comment]
This PR fixes it https://github.com/code-mancers/rapidfire/pull/85. Thanks @leonhooijer
