### ISSUE TITLE
undefined method `primary_key' for Fixnum:Class when using authentication from scratch

### ISSUE THREAD

**Issue by treehau5** [code-mancers/rapidfire#36]
This happens after a vanilla install, following all directions described in the readme, creating a basic survey with a question, then attempting to answer a question. 

-occurs whether or not you generate views or not
-occurs with rails 3 and 4

I am using ruby 2.1.5, also occurs with ruby 2.0

**Comment by iffyuva** [comment]
closing this one as there is no update.
