### ISSUE TITLE
add support for conditional inputs

### ISSUE THREAD

**Issue by iffyuva** [code-mancers/rapidfire#43]
requested by anil.

usecase:
- say if i have a dropdown with countries "india", "us", and
- subsequent dropdown is states. then this question is first question.

**Comment by iffyuva** [comment]
this requires bit of js fiddling i suppose.

**Comment by ssoulless** [comment]
Hi any update on this? I need to show/hide questions based on previous answers

**Comment by iffyuva** [comment]
@ssoulless i think your requirements are different from what i have listed here. can you explain your requirements?

**Comment by brunoocasali** [comment]
What about http://helpcenter.typeform.com/hc/en-us/articles/200045883 ? Like paid version of Typeform!
