### ISSUE TITLE
Override AnswerGroupsController#create to redirect to another page

### ISSUE THREAD

**Issue by donovki** [code-mancers/rapidfire#59]
Hi All,

At present, when someone completes the survey and clicks 'Save', it POSTs to AnswerGroupsController#create which ends in a redirect to question_groups_path.

What's your recommended way for overriding the default redirect_to in AnswerGroupsController#create to another page?

Thanks.

**Comment by iffyuva** [comment]
Thanks to @altherlex This PR https://github.com/code-mancers/rapidfire/pull/74 fixes it
