### ISSUE TITLE
Acts_as_surveyable?

### ISSUE THREAD

**Issue by alexmc6** [code-mancers/rapidfire#88]
Hi, 
This is a support request, not an issue, because I am trying to understand whether rapidfire will do what I need. 

As I understand it we have surveys, which are a bunch of questions, and an answer group which is a particular user's attempt to answer those questions. What I want is for a survey (and thus answer group of responses to that survey) to be associated with an arbitrary model, rather than users as a whole. 

For instance, imagine that we had a bunch of questions about a movie you just watched .I might ask the same questions about lots of movies, and not just one.

One possibility is that we include the id of the movie as an answer to a question that users cannot change. That would also require a model id to be an acceptable answer, but one which is specified by the server, not the user. I can't see that in the current list of types. 

Does anyone do this?

Thanks

**Comment by HarshwardhanSingh** [comment]
I think is it same as https://github.com/code-mancers/rapidfire/issues/69

**Comment by iffyuva** [comment]
@alexmc6 we will support this eventually. Thanks for opening issue. We will follow it up in #69
