### ISSUE TITLE
Make controllers before_filter free.

### ISSUE THREAD

**Issue by iffyuva** [code-mancers/rapidfire#9]
This helps in deriving from controllers, and specifying them {refer to `exp-multitenant-support` branch}, and adding filters the way user wants. At present, there is one before_filter `can_administer?`, and its too difficult to add any filter before it. One can do skip_before_filter `can_administer?` and redefine before_filter sequence, but user should be given more control w.r.t controllers.

**Comment by iffyuva** [comment]
@aksh93 can you pick this up?

**Comment by aksh93** [comment]
@iffyuva Yeah, let me go through it.
