### ISSUE TITLE
after attempt redirect

### ISSUE THREAD

**Issue by bnadav** [code-mancers/rapidfire#93]
Hi all,
How about adding a config option for 'after_attempt_path' - that sets the url to redirect to, after a successful attempt creation.
In PR#74 this is done using a decorator, but maybe it is easier for the integrating app to set this value in an initializer file. Something like this
  
  #Maip app : config/initializers/rapidfire_init.rb
  Rapidfire.config do | config |
    config.after_attempt_path = "/login"
  end

**Comment by iffyuva** [comment]
Thanks to @altherlex, this PR fixes it https://github.com/code-mancers/rapidfire/pull/74
@bnadav can you check latest master once?
